### ISSUE TITLE
Support for programmatic API in tests

### ISSUE THREAD

**Issue by newPOPE** [nextras/mail-panel#17]
Hi,

is there any change that mail-panel will implement something like this (https://github.com/captbaritone/codeception-mailcatcher-module#actions)?

It is very suitable in automatic tests.

**Comment by JanTvrdik** [comment]
That's very unlikely as it's out of the mail panel scope. Mail panel uses custom `IPersistentMailer` implementations. This is however pointless for testing where there is no need to store the mails in persistent storage. Writing simple mock for `IMailer` is usually enough.

I don't see any code in mail panel that could be reused for library for testing mails as these are quite different problems.

**Comment by newPOPE** [comment]
Ok, nevermind.
