### ISSUE TITLE
Allow IMailer service replacement

### ISSUE THREAD

**Issue by JanTvrdik** [nextras/mail-panel#18]
By using the recommended configuration

~~~yaml
services:
    nette.mailer: Nextras\MailPanel\FileMailer(%tempDir%/mail-panel-mails)
~~~

The following code will fail

~~~php
$container->removeService('nette.mailer');
$container->addService('nette.mailer', Mockery::mock(IMailer::class));
~~~

AFAIK the only possible solution is to change `MailPanel` typehint from `IPersistentMailer` to `IMailer` and ignore the mailer when not instance of `IPersistentMailer`. Also the configuration would need to be changed to 

~~~yaml
services:
    nette.mailer: 
        class: Nette\Mail\IMailer
        factory: Nextras\MailPanel\FileMailer(%tempDir%/mail-panel-mails)
~~~

**Comment by hrach** [comment]
I'm ok with chaning to IMailer typehint & doc.
