### ISSUE TITLE
Remove Nette\Object

### ISSUE THREAD

**Issue by sasule** [nextras/mail-panel#27]
Please abandon use of Nette\Object and switch to trait Nette\SmartObject.
Extension becomes incompatible with latest nette.

Sorry for not sending a PR, being at work right now ;-)

**Comment by matej21** [comment]
it's already fixed in master and 2.4.0-beta1 version, see https://github.com/nextras/mail-panel/commit/8250c4377d84fdfcb4a766d63d2044e5ac0d10f7

**Comment by sasule** [comment]
Thanks for a quick reply.
